# Generated by Django 5.2.4 on 2025-08-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_estudo', models.DurationField()),
                ('tempo_descanso', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sessao', models.IntegerField()),
                ('data_hora_inicio', models.TimeField()),
                ('data_hora_fim', models.TimeField()),
                ('ciclos_completos', models.IntegerField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pomodoro.materia')),
            ],
        ),
    ]
