# Generated by Django 5.2.4 on 2025-08-05 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='id_ciclo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='id_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_pomodoro.materia'),
        ),
    ]
