# Generated by Django 5.2.4 on 2025-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pomodoro', '0002_ciclo_id_ciclo_alter_sessao_id_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='assuntos',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='id_usuario',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='nome_materia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='tempo_estudado',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='id_materia',
            field=models.IntegerField(null=True),
        ),
    ]
