# Generated by Django 5.2.4 on 2025-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pomodoro', '0003_materia_assuntos_materia_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='id_ciclo',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='id_materia',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='id_sessao',
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='tempo_descanso',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='tempo_estudo',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='ciclos_completos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='data_hora_fim',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='data_hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
