# Generated by Django 5.2.4 on 2025-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pomodoro', '0004_remove_ciclo_id_ciclo_remove_materia_id_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='data_hora_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='data_hora_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
