# Generated by Django 5.2.4 on 2025-08-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pomodoro', '0005_alter_sessao_data_hora_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='id_materia',
        ),
        migrations.AlterField(
            model_name='sessao',
            name='ciclos_completos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='data_hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
