# Generated by Django 5.1.1 on 2025-08-19 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pomodoro', '0006_remove_sessao_id_materia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='tempo_descanso',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='tempo_estudo',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='ciclos_completos',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='qntd_sessoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='id_ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_pomodoro.ciclo'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='assuntos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome_materia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='tempo_estudado',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
