# Generated by Django 5.2.5 on 2025-08-21 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pomodoro', '0007_remove_ciclo_tempo_descanso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='app_pomodoro.materia'),
        ),
    ]
